id: AE8C87978
base_file: f5ACC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:17:36.740992
  last_modified_at: 2022-05-30 18:17:36.740999
